### ISSUE TITLE
database

### ISSUE THREAD

**Issue by theylovehowl** [nnyeh/Dahyun#1] opened 2021-02-24 18:32 UTC
I dont think users is tabled how do I do that.

Error: no such table:users
location: database.py

**Comment by nnyeh** [comment] 2021-02-24 19:06
this git doesnt have the database that i have, because im using this bot solely for my own server. i didnt really create this bot with the intention for others to use themselves, so you would need to create your own database.

here is the create statement of the database:
```
CREATE TABLE "users" (
	"user_id"	INTEGER,
	"lastfm_username"	TEXT,
	PRIMARY KEY("user_id")
)
```

**Comment by AliHaider20** [comment] 2021-05-02 00:21
None of my matter but if the issue is resolved plz closed it @nnyeh. It helps us to find other issues to solve on Github.

**Closed as completed** 2021-05-02 06:24 UTC
